### ISSUE TITLE
Problems with catching up data

### ISSUE THREAD

**Issue by NickyKL** [catalyst/moodle-mod_subcourse#25]
Hi, 
i dont know why, but I completed a course and the function, to catch up the data, doesnt work. When I wait the 10 Minutes, it works. That means to me, that the settings are not the reason for this.

Would it be possible to change the 10 minutes waiting-time? If a user finished a course, and goes back to the metacourse (with the subcourses) he will try to search for the reasen, it doesnt show up as completed.... Maybe sending a trigger, when the course is completed, then try to go and check, if the course is completed?

**Comment by mudrd8mz** [comment]
Do you have cron set up and working on your site?

**Comment by NickyKL** [comment]
Hi, I asked the IT the question. The answer was:

Yes: 
„*/5 *   * * *      root       cd /var/vhosts/dev-moodle; /usr/bin/php -f admin/cli/cron.php > /dev/null 2>&1”

**Comment by mudrd8mz** [comment]
Right. So my assumption is that after the course is completed, it can take up to 5 minutes for you Moodle to execute all the consequential actions.

**Comment by NickyKL** [comment]
does that mean, i cannot use the "Fetch now" Button?

**Comment by mudrd8mz** [comment]
You can, and it should work instantly. The thing is, it is the evaluation of the remote course completion that may take time.

If I understand it correctly, this is what is happening (I may be wrong):
1. You have a remote course with course completion set up.
2. A student finishes the course and your Snap theme shows them 100%. But Moodle does not have the course marked as "completed" yet as it does it asynchronously via cron job.
3. Even if you go to the associated Subcourse and use the Fetch now button, the Subcourse has nothing to fetch as the completion was not computed in the remote course yet.

However, if you are not referring to the completion status, but the grade itself, then Fetch now should always work instantly (synchronously).

**Comment by NickyKL** [comment]
Hm, that could explain it. We are not working with grades only with completion status/activity completion. I will talk to your IT-specialist and will let you know, what he thinks about it

**Comment by danmarsden** [comment]
no update from the reporter since the original report - closing for now, but please report a new issue if you think there is still an issue within the subcourse plugin - thanks.
