### ISSUE TITLE
Activity name not updated in gradebook when using edit shortcut

### ISSUE THREAD

**Issue by amjohnson46** [catalyst/moodle-mod_subcourse#30]
Hi David,

Here's a little bug I noticed. When I use the pencil icon editing shortcut (see screenshot) on the course page to edit the name of a subcourse, the item's name doesn't change in the gradebook. I check a quiz, and it works as expected. To get the name change to be applied for a subcourse, I have to open the actual Edit settings page, and there hit save. 

Steps to reproduce:
1. Edit the name of a subcourse item using the pencil edit shortcut.
2. Check in the gradebook that the name hasn't changed.
3. Open the settings page for the subcourse. 
4. Don't change anything. The name for the activity should display the edited name. Hit save.
5. Check the gradebook again. The name is now the edited name.

Not a biggie, just kind of annoying.

Thanks,
Aaron

![grafik](https://user-images.githubusercontent.com/35447514/51745441-1a07fd00-20a3-11e9-90b1-1dffb2847c8c.png)

**Comment by mudrd8mz** [comment]
Thanks Aaron for noticing this and for perfect steps to reproduce. I'll try to look at this. If anybody can provide a fix suggestion, you will be warmly welcome!

**Comment by amjohnson46** [comment]
Hi David,
As a related issue, but worse, if I duplicate a subcourse item, then change the name and linked course, the gradebook will continue to show the original item name. Using my trick above does not fix the issue anymore. I'm using Moodle 3.8.7 and the Subcourse Module 9.0.1 (2020090602). The links and grades are all correct, just the name displayed in the gradebook.
![Duplicated subcourses in gradebook](https://user-images.githubusercontent.com/35447514/109217130-0bf1a280-777b-11eb-81ea-0e1f165a8676.JPG)
Any ideas on how to fix it? I tried forcing all the Scheduled tasks related to grades and subcourse and purging all my caches. 
Thanks,
Aaron
