### ISSUE TITLE
Subcourse doesn't change to complete status

### ISSUE THREAD

**Issue by Anju0392** [catalyst/moodle-mod_subcourse#52]
Hi,

I was trying to add subcourse into one of the current course and I did everything as per the conditions that I added in the settings. Even though I finished my referenced course corresponding to the subcourse, the status of the subcourse is not changing to complete. But the progress is showing as 100% and course grade is 8, where I needed only 5 to pass the reference course.

![image](https://user-images.githubusercontent.com/48005554/180103136-5135829f-2c41-489a-9b73-de8b3760a9fd.png)

Would be great, if you could fix this :)

**Comment by srqwebguy1** [comment]
I am having the exact same issue. Did you ever get this resolved?

**Comment by danmarsden** [comment]
not really enough information here to be able to debug this - please test with the latest version and make sure you have cron running on your moodle site and if there's still an issue, please report a new tracker issue and make sure you include the Moodle version you are using and if you are using the latest version from github or an old version from the moodle.org plugins db - thanks!
