### ISSUE TITLE
Behat failures on Moodle 4

### ISSUE THREAD

**Issue by sharpchi** [catalyst/moodle-mod_subcourse#56]
Just been testing on Moodle 4.0.3 with PHP 8.0 and got the following Behat errors on the following Scenarios:
/var/www/html/mod/subcourse/tests/behat/auto_fetch_grades.feature:8
- And I follow "Unit course 1"
/var/www/html/mod/subcourse/tests/behat/completion_course.feature:45
/var/www/html/mod/subcourse/tests/behat/completion_course.feature:50
- And I add the "Self completion" block 
/var/www/html/mod/subcourse/tests/behat/course_page_display.feature:48
/var/www/html/mod/subcourse/tests/behat/course_page_display.feature:71
- And I navigate to "Edit settings" in current page administration
/var/www/html/mod/subcourse/tests/behat/fetch_percentage_grades.feature:111
/var/www/html/mod/subcourse/tests/behat/fetch_percentage_grades.feature:140
- And I press "Continue"
/var/www/html/mod/subcourse/tests/behat/hidden_grades.feature:49
- And I follow "Unit course 1"
/var/www/html/mod/subcourse/tests/behat/hidden_grades.feature:87
- And I follow "Unit course 1"
/var/www/html/mod/subcourse/tests/behat/instant_redirect.feature:53
- And I follow "Unit course 1"
/var/www/html/mod/subcourse/tests/behat/instant_redirect.feature:64
- And I follow "Unit course 1"

Most appear to be related to navigation changes in Moodle 4, so nothing broken - unit tests all passed.

**Comment by mudrd8mz** [comment]
Thanks Mark.

I can't promise I would have time to get to this anytime soon. Patches will be warmly welcome.

**Comment by danmarsden** [comment]
should be fixed now in Pull #62
